export const ACCESS_REQUEST = 'ACCES_REQUEST';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const REQUEST_PENDING = 'REQUEST_PENDING';
export const REQUEST_SUCCEED = 'REQUEST_SUCCEED';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
