export const GET_BUSINESS = 'GET_BUSINESS';
export const SET_BUSINESS = 'SET_BUSINESS';
export const GET_RAW_MATERIALS = 'GET_RAW_MATERIALS';
export const SET_RAW_MATERIALS = 'SET_RAW_MATERIALS';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCT_RAW_MATERIALS = 'SET_PRODUCT_RAW_MATERIALS';
